name: Unit Tests

on:
  push:
    branches:
      - '*'
    paths:
      - '**/*.py'
      - '**/*.c'
      - '.github/workflows/**'
  schedule:
    - cron: '0 0 */14 * *' # Runs every 14 days

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.8]

    steps:
    - name: Check Out Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        bash install.sh
      working-directory: ./

    - name: Run Unit Tests
      run: |
        python -m unittest discover -s tests -p "*_test.py"
      working-directory: ./